name: Greetings

on:
  push:
    branches:
      - 'mathijs'

jobs:
  greeting:
    runs-on: ubuntu-lates
    
    steps:
    - uses: cinotify/github-action@main
    - name: notify
      with:
        to: 'example@example.com'
        subject: 'building main'
        body: 'This is a notification from GitHub actions.'
